image: Visual Studio 2022
build: false

environment:
  matrix:
    - MINICONDA: C:\Miniconda39-x64
      PYTHON_VERSION: 3.9

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install tqdm openjpeg ruamel.yaml # for glymur
  - pip install -r test_requirements.txt -U
  - pip install -r requirements.txt -U
  - pip install .

cache:
  - '%MINICONDA%\envs\*'
  - '%MINICONDA%\pkgs\*'

test_script:
  - pytest tests/
